import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router'
import React, {useState, useEffect} from "react";
import { makeStyles } from '@material-ui/core/styles';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemText from '@material-ui/core/ListItemText';
import ListItemAvatar from '@material-ui/core/ListItemAvatar';
import Avatar from '@material-ui/core/Avatar';
import DescriptionIcon from '@material-ui/icons/Description';
import FastForwardIcon from '@material-ui/icons/FastForward';
import {Container} from "@material-ui/core";
import http from "../../api/client";
import BottomNavigation from "@material-ui/core/BottomNavigation";
import BottomNavigationAction from "@material-ui/core/BottomNavigationAction";
import RestoreIcon from "@material-ui/icons/Restore";
import FavoriteIcon from "@material-ui/icons/Favorite";
const useStyles = makeStyles((theme) => ({
    root: {
        width: 800,
        maxWidth:'80%',
        minWidth: 360,
        maxHeight:300,
        margin:'0 auto',
        backgroundColor: theme.palette.background.paper,
        marginTop:80
    },
    heading: {
        fontSize: theme.typography.pxToRem(15),
        fontWeight: theme.typography.fontWeightRegular,
    },
}));

export default function Archives() {
    const router = useRouter();
    const classes = useStyles();
    const [files,setFiles] = useState([]);
    useEffect(() => {
        const axiosObject = {
            url: `/`,
            method: "GET"
        };
        http(axiosObject)
            .then(response => {
                setFiles(response.data.response);
            })
            .catch(error => {
                console.log(error.response);

            });


    }, []);
    return (
        <>
            <Head>
                <title>Archives</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <BottomNavigation
                    value={1}
                    showLabels
                    className="navigation"
                >

                    <BottomNavigationAction label="Upload" icon={<RestoreIcon />} onClick={()=> router.push("/")}/>
                    <BottomNavigationAction label="Archives" icon={<FavoriteIcon />} onClick={()=> router.push("/archives")}/>
                </BottomNavigation>
                <List className={classes.root}>

                    {files.map((file)=>{
                        return (
                            <ListItem key={file[0]}>
                                <ListItemAvatar>
                                    <Avatar>
                                        <DescriptionIcon />
                                    </Avatar>
                                </ListItemAvatar>
                                <ListItemText primary={file[1].files[0]} secondary={'Last modified '+new Date(file[1].timestamps.mTime).toLocaleString()} />
                                <Link href={`/posts/${file[0]}`}>
                                    <FastForwardIcon />
                                </Link>
                            </ListItem>

                        );
                    })}
                </List>
            </Container>
        </>
    );
}