import { useRouter } from 'next/router'
import FileItem from "../../components/FileItem";
import Link from 'next/link';
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import React from "react";

const Post = () => {
    const router = useRouter();
    const { pid } = router.query;

    return (
        <div className={styles.container}>
            <Head>
                <title>Post: {pid}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Link href="/">
                    return
                </Link>
            </div>
            <main className={styles.main}>
                <p>Post: {pid}</p>
                <FileItem file={pid} key={pid}/>
            </main>
        </div>
    );

}

export default Post