import { useRouter } from 'next/router'
import FileItem from "../../components/FileItem";
import Link from 'next/link';
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import React, {useEffect,  useState} from "react";
import http from "../../api/client";
import useQuery from "../../services/useQuery";
import Button from '@material-ui/core/Button';

const Post = () => {
    const router = useRouter();
    const query = useQuery();
    console.log('router.query',router.query);
    const [token,setToken] = useState( router.query.token);
    const [originalCode,set_originalCode] = useState( "");
    const [minifiedCode,set_minifiedCode] = useState( "");
    const [originalTitle,set_originalTitle] = useState( "");
    const [minifiedTitle,set_minifiedTitle] = useState( "");

    useEffect(() => {
        console.log('token',token);
        if(!token){
            setToken(router.query.token);
            return;
        }

        const axiosObject = {
            url: `/${token}`,
            method: "GET"
        };
        http(axiosObject)
            .then(response => {
                console.log('response',response);
                try{
                    set_originalCode(response.data.content.files[0].content);
                    set_minifiedCode(response.data.content.files[1].content);
                    set_originalTitle(response.data.content.files[0].name);
                    set_minifiedTitle(response.data.content.files[1].name);
                }catch (e){

                }
            })
            .catch(error => {
                console.log(error.response);

            });


    }, [query,token]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Post:</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

               <div className={styles.main}>
                   <Button variant="contained" color="primary" onClick={() => router.back()}>
                       return
                   </Button>
                   <p>Post:</p>
                   <FileItem minifiedCode={minifiedCode} originalCode={originalCode} originalTitle={originalTitle} minifiedTitle={minifiedTitle}/>
               </div>

        </div>
    );

}

export default Post