import Head from 'next/head'
import Image from 'next/image'
import CssBaseline from '@material-ui/core/CssBaseline';
import styles from '../styles/Home.module.css'
import Container from '@material-ui/core/Container';
import { makeStyles } from '@material-ui/core/styles';
import List from '@material-ui/core/List';
import Link from 'next/link';
import ListItem from "@material-ui/core/ListItem";
import Typography from "@material-ui/core/Typography";
import ListItemText from "@material-ui/core/ListItemText";
import SettingsIcon from '@material-ui/icons/Settings';
import React from "react";

const useStyles = makeStyles((theme) => ({
  root: {
    width: '100%',
    // maxWidth: 360,
    backgroundColor: theme.palette.background.paper,
  },
  heading: {
    fontSize: theme.typography.pxToRem(15),
    fontWeight: theme.typography.fontWeightRegular,
  },
}));

export default function Home() {
  const classes = useStyles();
  const files = [1,2,3,4,5];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <React.Fragment>
          <CssBaseline />
          <Container maxWidth="xl">
            <List className={classes.root}>
                {files.map((file) => {
                  // return <>{file}</>;
                  return (

                           <>
                             <ListItem>
                             <Typography className={classes.heading}>{file}.</Typography>
                             <ListItemText primary="Photos" secondary="Jan 9, 2014"/>
                               <Link href={`/posts/${file}`} key={file}>
                                 <SettingsIcon color="action" />
                               </Link>
                             </ListItem>

                           </>

                  )

                })}
            </List>
          </Container>
        </React.Fragment>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
